### ISSUE TITLE
Bug: Different size windows

### ISSUE THREAD

**Issue by Viciooso** [glzr-io/glazewm#569] opened 2024-04-02 07:48 UTC
I have two screens, my laptop one 2160x1440 and 1920x1080. I've been testing this project and for some reason when i open firefox or the terminal the windows is sized to de 1440p one.

Also, will be great to be added alt + drag the windows and resize to.

**Comment by lars-berger** [comment] 2024-08-16 04:36
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:36 UTC
