### ISSUE TITLE
Make workspace as first class rather than monitor

### ISSUE THREAD

**Issue by vunhatchuong** [glzr-io/glazewm#501] opened 2024-01-08 05:47 UTC
Currently the monitor holds where the workspace is and not which workspace wants to be on which monitor.

So right now if my workspace `A` is on monitor 1 and workspace `B` on monitor 2, If I want `B` to be on my main monitor,
I have to input the following commands on my main monitor:
1. focus workspace A
2. move workspace right
3. focus workspace B
4. move workspace left

Ideally what I want to happen is, while on my main monitor:
1. focus workspace B
And that will put workspace A on my 2nd monitor.

**Comment by lars-berger** [comment] 2024-08-16 05:25
Duplicate of #271

**Closed by lars-berger** 2024-08-16 05:25 UTC
