### ISSUE TITLE
Bug: Windows extend below the bottom of the display when using 2 different monitors.

### ISSUE THREAD

**Issue by matsavage** [glzr-io/glazewm#592] opened 2024-04-22 07:45 UTC
I have a laptop with a 16x10 display, and often use it with a 16x9 external monitor as the main display.

When in this configuration, on the 16x9 display, the bottom of pages, particularly browsers extend beyond the bottom of the screen, making it impossible to scroll down lists of issues etc.

**Comment by lars-berger** [comment] 2024-08-16 04:35
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:35 UTC
