### ISSUE TITLE
[Bug] Regression in GlazeWM 3.4.0 overlaying with Taskbar

### ISSUE THREAD

**Issue by anthonymendez** [glzr-io/glazewm#790] opened 2024-10-13 00:03 UTC
### Describe the bug

Hello, I realize that this may not be the right place but I figured I report this considering GlazeWM users may also use Windhawk or other Taskbar modifying programs :)

With the recent update, I noticed that the overlay isn't working as expected with my custom taskbar. I've modified the taskbar with Windhawk using:
* Taskbar Clock Customization
* Taskbar height and icon size
* Taskbar Labels for Windows 11
* Taskbar on Top for Windows 11
* Windows 11 Taskbar Styler 

The big issue is that the windows go under the taskbar on my main monitor. Then when I adjust the padding to compensate for this, my 2nd monitor with no taskbar has a large gap at the top with the programs.

Version 3.3.0 Example:
![{601BEB82-FE81-4FDF-B14C-E8DEA705C965}](https://github.com/user-attachments/assets/9bcf0eb7-0fde-44f5-91fd-842244b5e4b6)

Version 3.4.0 Example:
![{DF409530-1560-43EB-98E4-D8D56C1F67BC}](https://github.com/user-attachments/assets/e56f6450-eadb-4084-8f04-76f0ea2c77ff)

My config.yaml:
[config.yaml.txt](https://github.com/user-attachments/files/17351869/config.yaml.txt)

### Version number

3.4.0

**Comment by Geobert** [comment] 2024-10-16 08:32
I can confirm with StartAllBack on Win 11

**Comment by isaac-varg** [comment] 2024-10-16 22:41
Also having this issue with  Windows 11 and Start11 with the taskbar positioned on top.
![image](https://github.com/user-attachments/assets/fe5d2c48-438d-4205-b713-46868c2b4c20)

**Comment by JonasWischeropp** [comment] 2024-10-18 07:33
Does it help to set `gaps.scale_with_dpi` to `false`?
```yaml
gaps:
    scale_with_dpi: false
```

**Comment by isaac-varg** [comment] 2024-10-18 15:33
Configuring `scale_with_dpi` to `false` did not seem to help. 

I attempted to change the `gaps.outer_gap.top` to a higher value to avoid the taskbar and the issue persisted. The issue did resolve when I move my taskbar to be positioned at the bottom.

**Comment by Dovias** [comment] 2024-11-01 18:17
Can confirm. As far i've tested it it seems to happen only in those cases where specified top outer gap is being set at around 50 px. Strangely enough this matches the windows 11 taskbar size for me. Top taskbar alignment are wonky on Windows 11 sadly :(

I'm pretty sure this can be fixed with some kind of hook to StartAllBack and ExplorerPatcher, since Windows 11 for some odd reason removed the taskbar alignment feature.

**Comment by Dovias** [comment] 2024-11-02 20:18
Update: after thorough investigation of the code, I found a bug inside GlazeWM handling of working_rect objects. For some odd reason taskbar adjustment offset becomes negative which causes this weird behaviour which I was able to fix temporarily on my dev build. I might do PR to fix this soon.

**Closed** 2024-11-14 00:39 UTC
Labels: type: bug
