### ISSUE TITLE
Can one workspace have two monitors assigned? 

### ISSUE THREAD

**Issue by franroa** [glzr-io/glazewm#548] opened 2024-02-27 13:17 UTC
Hi, I was trying to create a "dev" workspace where I have in one monitor my terminal and in other monitor my IDE. 
Is it possible to assign two monitors to one workspace?

Thanks!

**Comment by lars-berger** [comment] 2024-08-16 09:36
Duplicate of #525

**Closed by lars-berger** 2024-08-16 09:36 UTC
