### ISSUE TITLE
Incorrect window height in multiple monitor system

### ISSUE THREAD

**Issue by lesca** [glzr-io/glazewm#598] opened 2024-05-06 07:36 UTC
Hello,
Thanks for make this great project!

I am setting up this on Win11 with two monitors:
* Monitor 1: 2160x1440, scale 150%
* Monitor 2: 1920x1080, scale 100% (Primary)

I find the height of some winodow on Monitor 2 is **too high**, e.g., msedge, explorer. In this case, I cannot see the bottom of the window. The workaround is I have to maximize the window, but I cannot see the *bar* then. 

However, not all application has this problem, e.g. VS Code has correct height on Monitor 2.

Can you please advise how to fix this? Many thanks!

Regards,
Lesca

**Comment by INGCapaDev** [comment] 2024-05-13 15:58
I have the same issue, if I set the same scale to both monitors all works perfectly but my laptop screen it's small and if I lower the scale all become extremely small.

**Comment by PWillumsen** [comment] 2024-06-19 21:51
I have the same issue when using two monitors, one 3840 × 2160 150% scaling and one 2560×1440 100% scaling. Have not found a solution yet other than set them to same scaling.

**Comment by lars-berger** [comment] 2024-08-16 04:35
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:35 UTC
