### ISSUE TITLE
First(?) row of windows out of borders on scaled monitor

### ISSUE THREAD

**Issue by exic** [glzr-io/glazewm#446] opened 2023-11-09 14:01 UTC
I have one monitor scaled to 175%, one to 150%. Both seem to have issues with their borders, but only if the window is in the first column. The second window (window on the right) seems to be okay..
If the window in the first row is alone (or if there is only one window), its contents are out of the screen and I can't read or reach what's there. Particularly annoying with a terminal 😉

Seems like a bug?

Version 2.0.3

![image](https://github.com/glazerdesktop/GlazeWM/assets/242107/508af04c-51aa-427c-b37d-aacbacc6974e)

**Comment by Parsifa1** [comment] 2024-02-26 06:42
i have the same problem, it seems like there will be scaling issues in the part between the two monitors

**Comment by Parsifa1** [comment] 2024-02-26 06:54
It seems that this problem only occurs in 2.1.1. You can try to roll back to 2.1.0 and there will be no problem.

**Comment by lars-berger** [comment] 2024-08-16 04:40
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:40 UTC
