### ISSUE TITLE
Incorrect window size when moving to another monitor with different size

### ISSUE THREAD

**Issue by michie1** [glzr-io/glazewm#435] opened 2023-10-22 14:31 UTC
Currently I have two screens with equal resolutions, but different sizes. When moving windows to another monitor the problems occurs the height or width is incorrect. It looks like it's reusing the size it had at the previous monitor. I see in the code this problem is tackled before, but for me it still occurs. It's especially annoying when I've a website open with at the bottom a button, I move the window to another monitor and now the height of the window is larger than the monitor and therefore the button is not visible anymore.

**Comment by gtsherman** [comment] 2023-10-25 13:56
I have this issue, too. I used to be able to fix it by setting up a chain of moving the workspace, setting to floating, then setting back to tiling. Unfortunately, this stopped working with the reason release.

The only solution I've found is to move the window using e.g. the `move left` or `move right` command, and then moving it back. So the issue is specific to the `move workspace` command.

**Comment by robertmoelker** [comment] 2024-02-23 10:12
> I have this issue, too. I used to be able to fix it by setting up a chain of moving the workspace, setting to floating, then setting back to tiling. Unfortunately, this stopped working with the recent release.
> 
> The only solution I've found is to move the window using e.g. the `move left` or `move right` command, and then moving it back. So the issue is specific to the `move workspace` command.

@gtsherman Thanks for posting your workaround here! That's indeed working on the latest release. I had in some older versions as well but mostly managed to fix is automatically by switching full-screen to regular screen. For now (when it happens) the simple move command works great :)

**Comment by lars-berger** [comment] 2024-08-16 04:39
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:39 UTC
