### ISSUE TITLE
[Feature Request] Display specific binding modes and binding mode transparency

### ISSUE THREAD

**Issue by SlyCedix** [glzr-io/glazewm#555] opened 2024-03-06 17:49 UTC
I'm using workspaces with bind_to_monitor to create a full set of 10 workspaces for each of my 3 monitors. I'd like to set it up so that my `Alt+#` keybinds switch to the corresponding desktop on the focused monitor. 

Currently my workaround is creating a binding mode for each display entered with `Alt+Ctrl+#`, though this isn't ideal since there is no command transparency option in binding modes. To solve the lack of transparency, I duplicated my entire set of keybindings to the binding mode for each display, allowing me to use all of my keybindings regardless of what display mode I'm on. Alternatively I could have made them all one shot bindings that exited the binding mode upon focus switching or moving a window.

binding_mode objects should have a `transparent` property which, when set to true, maps all unbound keys to the none binding mode bindings.

The ability to execute a command on display focus change, or to directly map a binding mode to a specific focused display, would also streamline workflows like these immensely.

**Comment by lars-berger** [comment] 2024-08-16 09:12
The underlying issue sounds like a duplicate of #271 (activating workspaces on the focused monitor)

Being able to automatically enable a binding mode is now tracked at #675

**Closed by lars-berger** 2024-08-16 09:12 UTC
