### ISSUE TITLE
Firefox grows beyond bottom screen bounds when abutting taller workspace

### ISSUE THREAD

**Issue by DietBroccoli** [glzr-io/glazewm#565] opened 2024-03-28 11:35 UTC
I have a two-monitor configuration with resolutions of `2560x2880` & `3840x1600` respectively: 
![image](https://github.com/glzr-io/glazewm/assets/86387000/75b753a3-47e3-4287-8746-1155a97efa3e)

The following example will show that when my Firefox window abuts the taller workspace (to the left), it grows so large that elements with relative positioning slide down _(and eventually fall off of)_ the page.

## Normal: 
![image](https://github.com/glzr-io/glazewm/assets/86387000/f7cac723-49ed-46c4-8ee4-aab027e2ec10)

## Oversized:
![image](https://github.com/glzr-io/glazewm/assets/86387000/76f3aa3e-d469-42cc-a9cf-c955e6be09b9)

This also means that I cannot see the bottom of pages to which I've scrolled to the bottom, and this happens whether Firefox is the only window or not.  Firefox also appears normally when maximized, but returns to oversized when not.

No amount of shifting between workspaces or re-positioning fixes the issue of Firefox being oversized when abutting the taller workspace.

**Comment by Crackpotpower56** [comment] 2024-04-01 00:43
Had the same issue with thorium had to make it slightly smaller by adding.

  - command: "resize borders 0px -2px -2px -2px"
    match_process_name: "thorium"

Seems to be a conflict with Windows scaling on my end as i have my vertical at Portrait 100% scaling and my main at landscape with 150% as it is a 4K monitor.

**Comment by DietBroccoli** [comment] 2024-04-01 16:38
@Crackpotpower56 : Thanks for the suggestion.  I haven't been able to re-create my own issue since the day I posted this, but if I encounter it again I'll report back.

**Comment by lars-berger** [comment] 2024-08-16 04:38
Duplicate of #661

**Closed by lars-berger** 2024-08-16 04:38 UTC
