### ISSUE TITLE
[Possible Bug] Wrong window size when moving a window between workspaces with different display scale

### ISSUE THREAD

**Issue by liny01-nbsa** [glzr-io/glazewm#455] opened 2023-12-01 19:24 UTC
Thank you for making GlazeWM.

I have 3 monitors, 2 of which the display scale is set to 175%, and one set to 150%.

When I move a window from a monitor that's on a 175% scaled display, to a 150% scaled display, the top left of window is aligned right, but the size of window ended up wrong. Attachment is such an case.

If the movement happened from 150% to 175%, the size of the window expanded beyond the slot space.

It would be right sized, if the windows is minimized then restored. Or most of sometimes toggle the tiling direction.

<img width="1280" alt="wrong-size_2023-12-01_14-18-53" src="https://github.com/glazerdesktop/GlazeWM/assets/38985073/15737e99-f9d9-4d03-89b6-3a19b4f8186c">

**Comment by michie1** [comment] 2023-12-09 11:23
Related or possible duplicate: #435

**Comment by lars-berger** [comment] 2024-08-16 12:30
Duplicate of #661

**Closed by lars-berger** 2024-08-16 12:30 UTC
